job:
  package-manager: nuget
  allowed-updates:
    - update-type: all
  dependency-groups:
    - name: microsoft
      rules:
        patterns:
          - 'Microsoft.*'
  source:
    provider: github
    repo: rhyskoedijk/dependabot-test-nuget-update-not-possible
    directory: /
